<?php

/**
 * @file
 * Applies a fadeIn/Out effect on views that have "Ajax" enabled.
 */

/**
 * Implements hook_views_api().
 */
function views_ajax_fade_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_views_ajax_data_alter().
 *
 * @param array $commands
 *   An array of ajax commands
 * @param string $view
 *   The view which is requested.
 */
function views_ajax_fade_views_ajax_data_alter(&$commands, $view) {

  // Go deep into the array to get our available options.
  $options = $view->query->pager->display->display_options;

  // Intialize our settings variables.
  $use_fade = $options['vaf_use_fade'];
  $duration = $options['vaf_fade_duration'];

  // Replace Views' method replaceWith with our custom command
  // to replace the content with a fade. See: views_ajax_fade.js.
  if ($use_fade == "Yes") {
    foreach ($commands as &$command) {
      if ($command['method'] == 'replaceWith') {
        $command['command'] = 'pagerViewFade';
        $command['settings'] = array(
          'fade_duration' => $duration,
        );
      }
    }
  }
}
